-- Les contraintes d'integriter
ALTER TABLE DEPARTEMENT ADD CONSTRAINT fkRegion FOREIGN KEY(idRegion) REFERENCES REGION(idRegion);
ALTER TABLE COMMUNE ADD CONSTRAINT fkDepartement FOREIGN KEY(idDepartement) REFERENCES DEPARTEMENT(idDepartement);
ALTER TABLE PERSONNE ADD CONSTRAINT fkCommune FOREIGN KEY(idCommune) REFERENCES COMMUNE(idCommune);
ALTER TABLE TRAITEMENT ADD CONSTRAINT fkPersonne FOREIGN KEY(idPersonne) REFERENCES PERSONNE(idPersonne);
ALTER TABLE MEDECIN ADD CONSTRAINT fkEquipe FOREIGN KEY(idEquipe) REFERENCES EQUIPE(idEquipe);
ALTER TABLE TRAITEMENT ADD CONSTRAINT fkEquipe FOREIGN KEY(idEquipe) REFERENCES EQUIPE(idEquipe);
ALTER TABLE MEDECIN ADD CONSTRAINT fkHopital FOREIGN KEY(idHopital) REFERENCES HOPITAL(idHopital);
ALTER TABLE MEDECIN ADD CONSTRAINT fkEquipe FOREIGN KEY(idEquipe) REFERENCES EQUIPE(idEquipe);
ALTER TABLE REGION ADD CONSTRAINT ckRegion CHECK(REGION IN ('Agadez','Diffa','Dosso','Maradi','Niamey','Tahoua','Tillaberi','Zinder'));
ALTER TABLE PERSONNE ADD CONSTRAINT fkGenre CHECK(genre in(('M','F'));
ALTER table PERSONNE MODIFY nat  default 'NIGERIENNE';
ALTER TABLE PERSONNE ADD CONSTRAINT ckSitMat CHECK(situationMatrimoniale IN ('Marie','Celibataire','Divorcée'));
ALTER table PERSONNE MODIFY nbreEnfant default 0;
ALTER table PERSONNE ADD CONSTRAINT ckEtatEnfant CHECK(nbreEnfant BETWEEN 0 AND 20);
ALTER TABLE TRAITEMENT ADD CONSTRAINT ckEtatsante CHECK(etatSante IN ('gueri','decedé','rechute','traitement','retraitement','disparu'));