--Create a new Relational View
CREATE VIEW GLOBALE
AS ALLTABLES
SELECT * FROM HOPITALREFERENCE;
INNER JOIN DEPARTEMENT 
    ON DEPARTEMENT.idRegion=REGION.idRegion
INNER JOIN COMMUNE
    ON COMMUNE.idDepartement=DEPARTEMENT.idDepartement
INNER JOIN PERSONNE
    ON PERSONNE.idCommune=COMMUNE.idCommune
INNER JOIN TRAITEMENT
    ON TRAITEMENT.idEquipe=EQUIPE.idEquipe
    ON TRAITEMENT.idPersonne=PERSONNE.idPersonne
INNER JOIN MEDECIN
    ON MEDECIN.idHopital=HOPITAL.idHopital
    ON MEDECIN.idEquipe=EQUIPE.idEquipe